# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Fitzwilliam Museum Egyptian Coffins Project

locale: "en-GB"

title_separator: "-"

email: dejp3@cam.ac.uk

description: >- # The Fitzwilliam Egyptian Coffins project

words_per_minute: 200

baseurl: ""

url: "https://egyptiancoffins.org"

twitter_username: fitzwilliam_uk

github_username: fitzwilliammuseum

logo: https://egyptiancoffins.org/images/logos/logo.png

google_analytics: UA-3319190-12


lang: EN_GB
timezone: Europe/London
permalink: pretty
encoding: "utf-8"
read_time: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-mentions
  - jekyll-paginate

collections:
   coffins:
      output: true
   nakhtefmut:
      output: true
   nespawershefyt:
      output: true
   pakepu:
      output: true
   news:
      output: true
   team:
      output: true
   pop-ups:
      output: true
   miniature:
      output: true
   deathonthenile:
      output: true
   coffinsincontext:
      output: true
   beni-hasan:
      output: true
   deathblog:
      output: true
   portraits:
      output: true
   reuse:
      output: true
   catalogue:
      output: true
   testcatalogue:
      output: true
      
mailchimp-list: https://cam.us17.list-manage.com/subscribe/post?u=f30da66801c7549a27ffb3357&amp;id=741e719b5c

feed:
  collections:
    - pakepu
    - nespawershefyt
    - nakhtefmut
    - coffins
    - news
    - pop-ups
    - miniature
    - deathonthenile
    - coffinsincontext
    - beni-hasan
    - deathblog
    - reuse
    - testcatalogue

categories:
    - pakepu
    - nespawershefyt
    - nakhtefmut
    - miniature
    - beni-hasan
    - coffinsincontext
    - catalogue
    - testcatalogue

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
